### ISSUE TITLE
Uncaught TypeError: Cannot read property 'formats' of null

### ISSUE THREAD

**Issue by grigio** [aldenml/yt-lnk#2]
I tried to download this video http://www.youtube.com/watch?v=uTrsH0whUJc but I get the error above

**Comment by aldenml** [comment]
On it, I will let you know when it's fixed.

**Comment by aldenml** [comment]
Working now, fixed with https://github.com/aldenml/yt-lnk/commit/490671decb00b10f6e506f7c591642727882de9d
