### ISSUE TITLE
Search doesn't seem to work

### ISSUE THREAD

**Issue by MarcosBL** [aldenml/yt-lnk#3]
Or at least, it doesn't show a thing on screen, seems to be receiving an ampty array:

Autocomplete working

![Autocomplete working](http://i.imgur.com/46RQ7BI.png)

Console view

![Console view](http://i.imgur.com/5kHhi3J.png)

**Comment by aloisdg** [comment]
Same problem here.

**Comment by aldenml** [comment]
Thanks for reporting it. I will take a look.

**Comment by aldenml** [comment]
Fixed!
