### ISSUE TITLE
Some videos doesn't work

### ISSUE THREAD

**Issue by MarcosBL** [aldenml/yt-lnk#4]
For example, if you search for "sabina" and click on https://www.youtube.com/watch?v=cmmJ1uiRiUM 

You get an empty videoplayback.txt, no messages on console

**Comment by aldenml** [comment]
I don't expect it to work 100% due to the way I deal with the CORS problem. Can you retry in a few minutes?

**Comment by aloisdg** [comment]
I got an empty array in the console.

**Comment by MarcosBL** [comment]
Still the same, tested every couple of hours, I assume is a Yahoo Pipes problem ?

**Comment by aloisdg** [comment]
yt-link uses Yahoo Pipes? If so be careful:

> On 4 June 2015 it was announced that Pipes would be in read-only mode from 30 August 2015, and shut down on [30 September 2015](http://pipes.yqlblog.net/post/120705592639/pipes-end-of-life-announcement). Yahoo will not offer a paid version, but instead will shut down the program entirely.

**Comment by aldenml** [comment]
I'm using YQL and this particular video works for me.

**Comment by gubatron** [comment]
so it'll be working for little over a month then. :(

**Comment by MarcosBL** [comment]
Tested again, still doesn't work, shows the results, but download an empty .txt file if I click on any of the links.

**Comment by 1eddy87** [comment]
@aldenml is there anyway I can change your code so that I can download youtube videos?
I'm doing this server side at the moment however, bandwidth cost is ridiculous.
Any ideas/suggestions?

**Comment by aldenml** [comment]
unfortunately you will have the CORS limitation in any standard browser for a pure client solution. btw, this code is outdated and no maintained anymore.
